{
  "UI": {
    "showSolutionButton": "Show solution",
    "tryAgainButton": "Retry",
    "checkAnswerButton": "Check",
    "tipsLabel": "Show tip",
    "scoreBarLabel": "You got :num out of :total points",
    "tipAvailable": "Tip available",
    "feedbackAvailable": "Feedback available",
    "readFeedback": "Read feedback",
    "wrongAnswer": "Wrong answer",
    "correctAnswer": "Correct answer",
    "shouldCheck": "Should have been checked",
    "shouldNotCheck": "Should not have been checked",
    "noInput": "Please answer before viewing the solution"
  },
  "behaviour": {
    "enableRetry": true,
    "enableSolutionsButton": true,
    "singlePoint": true,
    "randomAnswers": true,
    "showSolutionsRequiresInput": true,
    "type": "auto",
    "confirmCheckDialog": false,
    "confirmRetryDialog": false,
    "autoCheck": false,
    "passPercentage": 100,
    "showScorePoints": true,
    "enableCheckButton": true
  },
  "overallFeedback": [
    {
      "from": 0,
      "to": 0,
      "feedback": "Wrong"
    },
    {
      "from": 1,
      "to": 99,
      "feedback": "Almost!"
    },
    {
      "from": 100,
      "to": 100,
      "feedback": "Correct!"
    }
  ],
  "question": "<code class=\"python\" lang=\"python\">raise ValueError</code>",
  "isSolutionPublic": true,
  "isFreeResponseSupported": false,
  "answers": [
    {
      "text": "<code class=\"python\" lang=\"python\">ValueError</code>",
      "correct": false,
      "tipsAndFeedback": {
        "tip": "",
        "chosenFeedback": "If an exception is raised without parenthesis, the exception class's constructor will be called without arguments.",
        "notChosenFeedback": ""
      }
    },
    {
      "text": "<code class=\"python\" lang=\"python\">NameError: name 'ValueError' is not defined</code>",
      "correct": false,
      "tipsAndFeedback": {
        "tip": "",
        "chosenFeedback": "ValueError is one of Python's built-in exceptions.",
        "notChosenFeedback": ""
      }
    },
    {
      "text": "<code class=\"python\" lang=\"python\">SyntaxError: Missing parenthesis in call to 'ValueError'</code>",
      "correct": true,
      "tipsAndFeedback": {
        "tip": "",
        "chosenFeedback": "An exception can be raised without providing an error message. In this case, the error message is empty, but the exception name is still printed.",
        "notChosenFeedback": ""
      }
    }
  ],
  "subContentId": "5e32591a-6061-475d-876c-b4b2e74399bc",
  "detailedSolution": "An exception can be raised without providing an error message. In this case, the error message is empty, but the exception name is still printed."
}